name: List Branches in Repo

# Trigger the workflow manually or on push to the main branch (or any other branch you prefer)
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  list_branches:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for this workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code in the repository

    - name: List local branches
      run: |
        echo "Listing local branches:"
        git branch

    - name: List remote branches
      run: |
        echo "Listing remote branches:"
        git branch -r
